version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  eureka-client:
    build:
      context: ./eureka-client
      dockerfile: Dockerfile
    ports:
      - "8090"
    environment:
      EUREKA_SERVER_URL: "http://eureka-server:8761/eureka/"
    networks:
      - microservices-net
    deploy:
      replicas: 3
    depends_on:
      - eureka-server

  service-discovery:
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    networks:
      - microservices-net

  order-postgres:
    image: postgres:15
    container_name: order_postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd1
      POSTGRES_DB: orderdb
    ports:
      - "5433:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data
    networks:
      - microservices-net

  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
    depends_on:
      - order-postgres
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-postgres:5432/orderdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pwd1
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_SERVER_URL: "http://eureka-server:8761/eureka/"
    deploy:
      replicas: 3
    ports:
      - "8080:8081"
    networks:
      - microservices-net

  inventory-postgres:
    image: postgres:15
    container_name: inventory_postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd2
      POSTGRES_DB: inventorydb
    ports:
      - "5434:5432"
    volumes:
      - inventory_pgdata:/var/lib/postgresql/data
    networks:
      - microservices-net

  inventory-service:
    build:
      context: ./inventory
      dockerfile: Dockerfile
    depends_on:
      - inventory-postgres
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-postgres:5432/inventorydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pwd2
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_SERVER_URL: "http://eureka-server:8761/eureka/"
    deploy:
      replicas: 3
    ports:
      - "8180:8080"
    networks:
      - microservices-net

  payment-postgres:
    image: postgres:15
    container_name: payment_postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd3
      POSTGRES_DB: paymentdb
    ports:
      - "5435:5432"
    volumes:
      - payment_pgdata:/var/lib/postgresql/data
    networks:
      - microservices-net

  payment-service:
    build:
      context: ./payment
      dockerfile: Dockerfile
    depends_on:
      - payment-postgres
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-postgres:5432/paymentdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pwd3
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_SERVER_URL: "http://eureka-server:8761/eureka/"
    deploy:
      replicas: 3
    ports:
      - "8280:8082"
    networks:
      - microservices-net

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-net

  product-service:
    build:
      context: ./product
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - eureka-server
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/productdb
      EUREKA_SERVER_URL: "http://eureka-server:8761/eureka/"
    deploy:
      replicas: 3
    ports:
      - "8380:8083"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  order_pgdata:
  inventory_pgdata:
  payment_pgdata:
  mongo_data:
