server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    httpclient:
      connect-timeout: 2000
      response-timeout: 5s
      pool:
        max-connections: 1000
        acquire-timeout: 5000
        max-idle-time: 15s
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true
logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO
