spring.application.name=inventory
spring.datasource.url=jdbc:postgresql://inventory-postgres:5432/inventorydb
spring.datasource.username=user
spring.datasource.password=pwd2
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8080